let database;
let characters;
const storedDatabase = localStorage.getItem('database');
// console.log(storedDatabase);
if (storedDatabase !== null && Object.keys(JSON.parse(storedDatabase)).length === 478) { 
    database = JSON.parse(storedDatabase);
    characters = Object.keys(database);
}
else {
    // console.log('database size: ' + Object.keys(JSON.parse(storedDatabase)).length)
    // console.log('database is reloaded');
    const DATABASE = { // some characters have more than one CangJie code, this database only include ~500 characters
        一:	'm',
        丁:	'mn',
        丂:	'mvs',
        七:	'p',
        万:	'ms',
        丈:	'jk',
        三:	'mmm',
        上:	'ym',
        下:	'my',
        丌:	'ml',
        不:	'mf',
        与:	'ysm',
        丏:	'mlvs',
        丐:	'myvs',
        丑:	'ng',
        丒:	'skm',
        专:	'qni',
        且:	'bm',
        丕:	'mfm',
        世:	'pt',
        丗:	'tj',
        丘:	'om',
        丙:	'mob',
        业:	'tc',
        丛:	'oom',
        东:	'kd',
        丝:	'vvm',
        丞:	'nem',
        丟:	'mgi',
        丠:	'lpm',
        両:	'mub',
        丢:	'hgi',
        丣:	'mlls',
        两:	'moob',
        严:	'mtch',
        並:	'ttc',
        丧:	'gcv',
        个:	'ol',
        丫:	'cl',
        丬:	'lim',
        中:	'l',
        丮:	'nq',
        丯:	'qj',
        丰:	'qj',
        丱:	'vlllm',
        串:	'll',
        丳:	'llww',
        临:	'lloa',
        丵:	'tctj',
        丸:	'kni',
        丹:	'by',
        为:	'iksi',
        主:	'yg',
        丼:	'tti',
        丽:	'mbib',
        丽:	'mmbib',
        举:	'fcq',
        乂:	'k',
        乃:	'nhs',
        久:	'no',
        乇:	'hp',
        么:	'hi',
        义:	'ik',
        之:	'ino',
        乌:	'pvsm',
        乍:	'os',
        乎:	'hfd',
        乏:	'hino',
        乐:	'hvd',
        乒:	'omh',
        乓:	'omi',
        乔:	'hkll',
        乕:	'hqb',
        乖:	'hjlp',
        乗:	'hjtd',
        乘:	'hdlp',
        乙:	'n',
        乜:	'ps',
        九:	'kn',
        乞:	'on',
        也:	'pd',
        习:	'sim',
        乡:	'vvh',
        乢:	'uu',
        乣:	'viu',
        乤:	'myn',
        乥:	'hcn',
        书:	'ids',
        乧:	'yjn',
        乨:	'iru',
        乩:	'yru',
        乪:	'nw',
        乫:	'krn',
        乬:	'ssn',
        乭:	'mrn',
        乮:	'hln',
        乯:	'hfdn',
        买:	'nyk',
        乱:	'hru',
        乲:	'ion',
        乲:	'mon',
        乳:	'bdu',
        乴:	'qln',
        乵:	'yju',
        乶:	'ibn',
        乷:	'ehn',
        乸:	'pdwyi',
        乹:	'jju',
        乺:	'hln',
        乻:	'yyn',
        乼:	'egn',
        乽:	'jan',
        乾:	'jjon',
        乿:	'bfu',
        亀:	'nwlu',
        亁:	'jjon',
        亂:	'bbu',
        亃:	'fqu',
        亄:	'gtu',
        了:	'nn',
        予:	'ninn',
        争:	'nsd',
        亊:	'jfln',
        事:	'jlln',
        二:	'mm',
        亍:	'mmn',
        于:	'md',
        亏:	'mmvs',
        亐:	'mjs',
        云:	'mmi',
        互:	'mvnm',
        亓:	'mml',
        五:	'mdm',
        井:	'tt',
        亖:	'mmmm',
        亗:	'umm',
        亘:	'mam',
        亙:	'mbm',
        亚:	'mtc',
        些:	'ypmm',
        亜:	'mllm',
        亝:	'iiim',
        亞:	'mllm',
        亟:	'mem',
        亟:	'nem',
        亡:	'yv',
        亢:	'yhn',
        交:	'yck',
        亥:	'yvho',
        亦:	'ylnc',
        产:	'yth',
        亨:	'yrnn',
        亩:	'yw',
        亪:	'ycmo',
        享:	'yrnd',
        京:	'yrf',
        亭:	'yrbn',
        亮:	'yrbn',
        亮:	'yrbu',
        亯:	'yra',
        亰:	'yaf',
        亱:	'yoam',
        亲:	'ytd',
        亳:	'yrbp',
        亴:	'yrbn',
        亵:	'yqiv',
        亶:	'ywrm',
        亷:	'yhxc',
        亸:	'ydcwj',
        亹:	'yhbm',
        人:	'o',
        亽:	'oi',
        亾:	'vo',
        亿:	'on',
        什:	'oj',
        仁:	'omm',
        仂:	'oks',
        仃:	'omn',
        仄:	'mo',
        仅:	'oe',
        仆:	'oy',
        仇:	'okn',
        仈:	'oc',
        仉:	'ohn',
        今:	'oin',
        介:	'oll',
        仌:	'oo',
        仍:	'onhs',
        从:	'oo',
        仏:	'oi',
        仐:	'oj',
        仑:	'op',
        仒:	'oy',
        仓:	'osu',
        仔:	'ond',
        仕:	'og',
        他:	'opd',
        仗:	'ojk',
        付:	'odi',
        仙:	'ou',
        仚:	'ou',
        仛:	'ohp',
        仜:	'om',
        仝:	'om',
        仞:	'oshi',
        仟:	'ohj',
        仠:	'omj',
        仡:	'oon',
        仢:	'opi',
        代:	'oip',
        令:	'oini',
        以:	'vio',
        仦:	'of',
        仧:	'ymo',
        仨:	'ommm',
        仩:	'oym',
        仪:	'oik',
        仫:	'ohi',
        们:	'olis',
        仭:	'osk',
        仮:	'ohe',
        仯:	'ofh',
        仰:	'ohvl',
        仱:	'ooin',
        仲:	'ol',
        仳:	'opp',
        仴:	'ob',
        仵:	'ooj',
        件:	'ohq',
        价:	'ooll',
        仸:	'ohk',
        仹:	'oqj',
        仺:	'osm',
        仺:	'osm',
        任:	'ohg',
        仼:	'omg',
        份:	'ocsh',
        仾:	'omvm',
        仿:	'oyhs',
        伀:	'oci',
        企:	'oylm',
        伂:	'ojb',
        伃:	'onin',
        伄:	'onl',
        伅:	'opu',
        伆:	'ophh',
        伇:	'ohne',
        伈:	'op',
        伉:	'oyhn',
        伊:	'osk',
        伋:	'onhe',
        伌:	'omsu',
        伍:	'omdm',
        伎:	'oje',
        伏:	'oik',
        伐:	'oi',
        休:	'od',
        伒:	'ohml',
        伓:	'omf',
        伔:	'obhu',
        伕:	'oqo',
        伖:	'oke',
        众:	'ooo',
        优:	'oiku',
        伙:	'of',
        会:	'ommi',
        伛:	'osk',
        伜:	'oknj',
        伝:	'ommi',
        伞:	'ofj',
        伟:	'oqs',
        传:	'oqni',
        伡:	'okq',
        伢:	'omvh',
        伣:	'obhu',
        伤:	'ooks',
        伥:	'opo',
        伦:	'oop',
        伧:	'oosu',
        伨:	'opmm',
        伩:	'oyk',
        伪:	'oiks',
        伫:	'ojm',
        伬:	'oso',
        伭:	'oyvi',
        伮:	'ove',
        伯:	'oha',
        估:	'ojr',
        伱:	'oof',
        伲:	'osp',
        伳:	'opt',
        伴:	'ofq',
        伵:	'owc',
        伶:	'ooii',
        伷:	'olw',
        伸:	'olwl',
        伹:	'obm',
        伺:	'osmr',
        伻:	'omfj',
        似:	'ovio',
        伽:	'oksr',
        伾:	'omfm',
        伿:	'orc',
        佀:	'orlr',
        佁:	'oir',
        佂:	'omym',
        佃:	'ow',
        佄:	'otm',
        佅:	'ojd',
        但:	'oam',
        佇:	'ojmn',
        佈:	'oklb',
        佉:	'ogi',
        佊:	'odhe',
        佋:	'oshr',
        佌:	'oymp',
        位:	'oyt',
        低:	'ohpm',
        低:	'ohvi',
        住:	'oyg',
        佐:	'okm',
        佑:	'okr',
        佒:	'olbk',
        体:	'odm',
        佔:	'oyr',
        何:	'omnr',
        佖:	'oph',
        佗:	'ojp',
        佘:	'ommf',
        余:	'omd',
        佚:	'ohqo',
        佛:	'olln',
        作:	'oos',
        佝:	'opr',
        佞:	'ommv',
        佟:	'ohey',
        你:	'onf',
        佡:	'oou',
        佢:	'oss',
        佣:	'obq',
        佤:	'omvn',
        佥:	'omfm',
        佦:	'omr',
        佧:	'oymy',
        佨:	'opru',
        佩:	'ohnb',
        佪:	'owr',
        佫:	'oher',
        佬:	'ojkp',
        佭:	'oheq',
        佮:	'oomr',
        佯:	'otq',
        佰:	'oma',
        佱:	'ommm',
        佲:	'onir',
        佳:	'ogg',
        佴:	'osj',
        併:	'ott',
        佶:	'ogr',
        佷:	'oav',
        佸:	'ohjr',
        佹:	'onmu',
        佺:	'oomg',
        佻:	'olmo',
        佼:	'oyck',
        佽:	'ommo',
        佾:	'ocb',
        使:	'ojlk',
        侀:	'omtn',
        侁:	'ohgu',
        侂:	'oihp',
        侃:	'orhu',
        侄:	'omig',
        侅:	'oyvo',
        來:	'doo',
        侇:	'okn',
        侈:	'onin',
        侉:	'okms',
        侊:	'ofmu',
        例:	'omnn',
        侌:	'oini',
        侍:	'ogdi',
        侎:	'ofd',
        侏:	'ohjd',
        侐:	'ohbt',
        侑:	'okb',
        侒:	'ojv',
        侓:	'olq',
        侔:	'oihq',
        侕:	'ombl',
        侖:	'ombt',
        侗:	'obmr',
        侘:	'ojhp',
        侙:	'oipm',
        侚:	'opa',
        供:	'otc',
        侜:	'ohby',
        依:	'oyhv',
        侞:	'ovr',
        侟:	'okld',
        侠:	'okt',
        価:	'omlw',
        侢:	'omgb',
        侣:	'orr',
        侤:	'ojks',
        侥:	'ojpu',
        侦:	'oybo',
        侧:	'obon',
        侨:	'ohkl',
        侩:	'oomi',
        侪:	'oykl',
        侫:	'oyvv',
        侬:	'ohbv',
        侭:	'osoy',
        侮:	'oowy',
        侯:	'onmk',
        侰:	'oskr',
        侱:	'orhg',
        侲:	'ommv',
        侳:	'ooog',
        侴:	'omnn',
        侵:	'osme',
        侶:	'orhr',
        侷:	'ossr',
        侸:	'omrt',
        侹:	'onkg',
        侺:	'ouon',
        侻:	'ocru',
        侼:	'ojbd',
        侽:	'owks',
        侾:	'ojkd',
        便:	'omlk',
        俀:	'obv',
        俁:	'orvk',
        係:	'ohvf',
        促:	'oryo',
        俄:	'ohqi',
        俅:	'oije',
        俆:	'oomd',
        俇:	'okhg',
        俈:	'ohgr',
        俉:	'ommr',
        俊:	'oice',
        俋:	'orau',
        俌:	'oijb',
        俍:	'oiav',
        俎:	'oobm',
        俏:	'ofb',
        俐:	'ohdn',
        俑:	'onib',
        俒:	'ojmu',
        俓:	'omvm',
        俔:	'obuu',
        俕:	'ojd',
        俖:	'omfr',
        俗:	'ocor',
        俘:	'obnd',
        俙:	'okkb',
        俚:	'owg',
        俛:	'onau',
        俜:	'olws',
        保:	'ord',
        俞:	'ombn',
        俟:	'oiok',
        俠:	'okoo',
        信:	'oymr',
        俢:	'oheh',
        俣:	'ormk',
        俤:	'ocnh',
        俥:	'ojwj',
        俦:	'oqki',
        俧:	'ogp',
        俨:	'omth',
        俩:	'omob',
        俪:	'ombb',
        俫:	'odt',
        俬:	'ohdi',
        俭:	'oomm',
        修:	'olhh',
        修:	'oloh',
        俯:	'oioi',
        俰:	'ohdr',
        俱:	'obmc',
        俲:	'oyks',
        俳:	'olmy',
    }
    database = DATABASE;
    characters = Object.keys(DATABASE);
    localStorage.setItem('database', JSON.stringify(DATABASE))
}

const chart = {
    q : '手',
    w : '田',
    e : '水',
    r : '口',
    t : '廿',
    y : '卜',
    u : '山',
    i : '戈',
    o : '人',
    p : '心',
    a : '日',
    s : '尸',
    d : '木',
    f : '火',
    g : '土',
    h : '竹',
    j : '十',
    k : '大',
    l : '中',
    z : 'Z',
    x : '難',
    c : '金',
    v : '女',
    b : '月',
    n : '弓',
    m : '一'
}

let randomCharacter = '';

const inputBox = document.getElementById('inputBox');
const character = document.getElementById('character');
const answer = document.getElementById('answer');
const revealButton = document.getElementById('revealButton'); 

if (!sessionStorage.getItem('prev')) {
    // console.log('start session storage');
    sessionStorage.setItem('prev', 0);
}

document.addEventListener('compositionupdate', (event) => {
    if (event.data.length > sessionStorage.getItem('prev')) {
        sessionStorage.setItem('prev', event.data.length);
        // console.log('>', sessionStorage.getItem('prev'));
    }
    else {
        sessionStorage.setItem('prev', event.data.length);
        // console.log('< or =', sessionStorage.getItem('prev'));
        return;
    }
        
    const lastCharacter = event.data[event.data.length - 1];
    const pressedKey = Object.keys(chart).find(key => chart[key] === lastCharacter);
    const virtualKey = document.querySelector(`[data-key="${pressedKey}"]`);
    if (virtualKey) {
        virtualKey.classList.add('pressed');
        setTimeout(() => {
            virtualKey.classList.remove('pressed');
        }, 100)
    }
});


inputBox.addEventListener('keyup', (event) => {
    if (event.key === 'Enter') {
       check();
    }
})

revealButton.addEventListener('click', () => {
    answer.innerText = database[randomCharacter].split('').map(letter => chart[letter]).join('');
    answer.style.display === 'none'
    ?
    answer.style.display = 'block'
    :
    answer.style.display = 'none';
})

function check() {
    if (inputBox.value === character.innerText) {
        generator();
        inputBox.value = '';
        answer.style.display = 'none';
    } 
}

function generator() {
   randomCharacter = characters[Math.floor(Math.random() * characters.length)];
   character.innerText = randomCharacter;
}

generator();
